name: 'oncology_dbt'
version: '1.0.0'
config-version: 2

profile: 'oncology_dbt'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  oncology_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table